"""Added event_preview as FK to images

Revision ID: bb31e7906372
Revises: 1f89ced8ee46
Create Date: 2025-02-03 16:38:33.159665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb31e7906372'
down_revision = '1f89ced8ee46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('event_preview',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='event_preview::integer')
        batch_op.create_foreign_key(None, 'images', ['event_preview'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('event_preview',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.drop_table('images')
    # ### end Alembic commands ###
